version: ^0.2.0 || @head
export: |

    project "Slacking"

        kind "StaticLib"

        zpm.export [[           
            zpm.uses "Zefiros-Software/cURL"

            includedirs "include"
            cppdialect "C++11"
            defines "NOMINMAX"
        ]]
